name: Build Docker Image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run build.sh
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Tag Docker Image
        run: docker tag onlinejudge-backend "$REGISTRY_URL/onlinejudge-backend"

      - name: Log in to Docker Registry
        run: echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" -u "$REGISTRY_USERNAME" --password-stdin

      - name: Push Docker Image
        run: docker push "$REGISTRY_URL/onlinejudge-backend"